const sideViewActionTypes = {
  FETCH_SIDEVIEW_MOVIE_START: "FETCH_SIDEVIEW_MOVIE_START",
  FETCH_SIDEVIEW_MOVIE_SUCCESS: "FETCH_SIDEVIEW_MOVIE_SUCCESS",
  FETCH_SIDEVIEW_MOVIE_FAILED: "FETCH_SIDEVIEW_MOVIE_FAILED",
};

export default sideViewActionTypes;
